language: cpp

os:
    - linux

compiler:
    - gcc
    - clang

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install qt5-default

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake

before_script:
    - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++

    - export CC=/usr/bin/gcc-6
    - export CXX=/usr/bin/g++-6

    - mkdir build
    - cd build
    - cmake ..

script: make